# Generated by Django 3.2 on 2022-09-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_login_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social_login_type',
            field=models.IntegerField(blank=True, help_text='1. Facebook, 2. Google', null=True),
        ),
    ]
