# Generated by Django 3.2 on 2022-10-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_otp_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter the tittle name', max_length=30, null=True, unique=True)),
                ('file', models.FileField(blank=True, help_text='Select file', null=True, upload_to='media/')),
                ('is_deleted', models.BooleanField(default=False, help_text='to delete the music')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, help_text='active')),
            ],
        ),
    ]
