# Generated by Django 3.2 on 2022-10-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(blank=True, help_text='Select file', null=True, upload_to='sounds/'),
        ),
    ]
