# Generated by Django 3.2 on 2022-10-18 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_music_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_default_sounds', to='users.music'),
        ),
    ]
