# Generated by Django 3.2 on 2022-10-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_default_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='sequence_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
