# Generated by Django 3.2 on 2022-12-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userrevenuecatmapper_usersubscriptiondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptiondetails',
            name='ends_on',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscriptiondetails',
            name='starts_on',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
