# Generated by Django 3.2 on 2022-12-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20221214_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptiondetails',
            name='event_type',
            field=models.CharField(blank=True, default='RENEWAL', max_length=100, null=True),
        ),
    ]
