version: '3.7'

services:
  backend:
    build:
      context: .
    volumes:
      - static_data:/backend/staticfiles
      - "./dist/media:/backend/media" # map to local machine
    env_file: # if .env in root, we have to show .env here must
      - ./.env
    depends_on:
      - db

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/backend/staticfiles
      - "./dist/media:/backend/media" # map to local machine
    ports:
      - "80:80"
    env_file: # if .env in root, we have to show .env here must
      - ./.env
    depends_on:
      - backend
      - db
  db:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
volumes:
  static_data:
  database: