# Generated by Django 3.2 on 2022-09-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20220912_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='updated_at',
        ),
    ]
