# Generated by Django 3.2 on 2022-09-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20220912_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='is_active',
            field=models.BooleanField(default=False, help_text='active'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='to delete the pomodoro'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
