# Generated by Django 3.2 on 2022-09-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20220912_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeline',
            old_name='count',
            new_name='code',
        ),
    ]
