# Generated by Django 3.2 on 2022-09-13 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0006_rename_count_timeline_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter the name', max_length=30, null=True, unique=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='to delete the Type')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, help_text='active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category_type', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
