# Generated by Django 3.2 on 2022-09-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type_image',
            field=models.FileField(blank=True, help_text='Select file', null=True, upload_to='media/'),
        ),
    ]
