# Generated by Django 3.2 on 2022-09-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_tags_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tags',
            unique_together=set(),
        ),
    ]
