# Generated by Django 3.2 on 2022-11-01 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0015_alter_tags_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_timeline', to=settings.AUTH_USER_MODEL),
        ),
    ]
