# Generated by Django 3.2 on 2022-11-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
