# Generated by Django 3.2 on 2022-11-11 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_categoryemoji_typeemoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryemoji',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='typeemoji',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_emoji', to='common.categoryemoji'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_emoji', to='common.typeemoji'),
        ),
    ]
