# Generated by Django 3.2 on 2022-11-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_auto_20221111_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Name'),
        ),
    ]
