# Generated by Django 3.2 on 2022-11-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(blank=True, help_text='Enter the name', max_length=30, null=True),
        ),
    ]
