# Generated by Django 3.2 on 2022-12-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_messageemoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageemoji',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
