# Generated by Django 3.2 on 2022-09-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
