# Generated by Django 3.2 on 2022-09-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Enter the template name', max_length=30, null=True, unique=True)),
                ('total_time', models.TimeField(auto_now_add=True)),
                ('elapsed_time', models.TimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0, help_text='pomodoro count')),
                ('completed', models.BooleanField(default=True, help_text='pomodoro status')),
                ('is_deleted', models.BooleanField(default=False, help_text='to delete the pomodoro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
