# Generated by Django 3.2 on 2022-09-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0002_auto_20220909_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodoro',
            name='is_active',
            field=models.BooleanField(default=False, help_text='active'),
        ),
    ]
