# Generated by Django 3.2 on 2022-09-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0004_auto_20220909_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodoro',
            name='elapsed_time',
        ),
        migrations.RemoveField(
            model_name='pomodoro',
            name='total_time',
        ),
    ]
