# Generated by Django 3.2 on 2022-09-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0006_auto_20220909_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodoro',
            name='total_time',
            field=models.BigIntegerField(default=1500),
        ),
    ]
