# Generated by Django 3.2 on 2022-09-19 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pomodoro', '0007_alter_pomodoro_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodoro',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pomodoro', to=settings.AUTH_USER_MODEL),
        ),
    ]
