# Generated by Django 3.2 on 2022-10-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0008_pomodoro_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodoro',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
