# Generated by Django 3.2 on 2022-10-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0009_pomodoro_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodoro',
            name='completed_cycle_count',
            field=models.IntegerField(default=0, help_text='completed pomodoro count'),
        ),
    ]
