# Generated by Django 3.2 on 2022-10-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0012_auto_20221019_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodoro',
            name='is_chime_selected',
            field=models.BooleanField(default=True),
        ),
    ]
