# Generated by Django 3.2 on 2022-12-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0013_alter_pomodoro_is_chime_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodoro',
            name='name',
            field=models.CharField(blank=True, help_text='Enter the tittle name', max_length=30, null=True),
        ),
    ]
