# Generated by Django 3.2 on 2022-04-20 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenge', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='friendinvitationchallange',
            name='invitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_invitation_challange', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendinvitationchallange',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendchallenge',
            name='category',
            field=models.ManyToManyField(blank=True, to='common.Category'),
        ),
        migrations.AddField(
            model_name='friendchallenge',
            name='challenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_challenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendchallenge',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenged_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendchallenge',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_challenge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendchallenge',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_challenge', to='common.timeline'),
        ),
        migrations.AlterUniqueTogether(
            name='friendinvitationchallange',
            unique_together={('challenge', 'email')},
        ),
    ]
