# Generated by Django 3.2 on 2022-04-26 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0003_alter_friendinvitationchallange_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendchallenge',
            name='friend',
        ),
        migrations.AddField(
            model_name='friendchallenge',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='challenged_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
