# Generated by Django 3.2 on 2022-09-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_auto_20220426_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendchallenge',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
