# Generated by Django 3.2 on 2022-11-03 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20221102_1132'),
        ('challenge', '0007_alter_friendchallenge_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendchallenge',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.type'),
        ),
        migrations.RemoveField(
            model_name='friendchallenge',
            name='category',
        ),
        migrations.AddField(
            model_name='friendchallenge',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.category'),
        ),
    ]
