# Generated by Django 3.2 on 2022-11-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_units_is_active'),
        ('challenge', '0008_auto_20221103_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendchallenge',
            name='goal_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_challenge', to='common.units'),
        ),
        migrations.AddField(
            model_name='friendchallenge',
            name='goal_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
