# Generated by Django 3.2 on 2022-11-17 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_auto_20221110_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('goal_value', models.CharField(blank=True, max_length=10, null=True)),
                ('target_goal_value', models.CharField(blank=True, max_length=10, null=True)),
                ('is_skipped', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_details', to='challenge.friendchallenge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
