# Generated by Django 3.2 on 2022-11-18 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_goaldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendchallenge',
            name='parent_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_friend_challenge', to='challenge.friendchallenge'),
        ),
    ]
