# Generated by Django 3.2 on 2022-11-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0012_friendchallenge_is_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendchallenge',
            name='is_reminder',
        ),
        migrations.AddField(
            model_name='goaldetail',
            name='is_reminder',
            field=models.BooleanField(default=True),
        ),
    ]
