# Generated by Django 3.2 on 2022-11-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0013_auto_20221118_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendchallenge',
            name='is_reminder',
            field=models.BooleanField(default=True),
        ),
    ]
