# Generated by Django 3.2 on 2022-11-24 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0015_alter_friendinvitationchallange_is_accepted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendinvitationchallange',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='friendinvitationchallange',
            name='email',
        ),
        migrations.RemoveField(
            model_name='friendinvitationchallange',
            name='facebook_response',
        ),
        migrations.RemoveField(
            model_name='friendinvitationchallange',
            name='invited_via',
        ),
    ]
