# Generated by Django 3.2 on 2022-11-28 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0013_alter_pomodoro_is_chime_selected'),
        ('todo', '0004_todo_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0016_auto_20221124_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.IntegerField(blank=True, help_text='1 - Todo, 2 - Pomodoro, 3- Self Challenge, 4 - Friend Challenge', null=True)),
                ('friend_challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_challenge_completion_details', to='challenge.friendchallenge')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pomodoro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pomodoro.pomodoro')),
                ('self_challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_challenge_completion_details', to='challenge.friendchallenge')),
                ('todo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.todo')),
            ],
        ),
    ]
