# Generated by Django 3.2 on 2022-11-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0017_completiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='completiondetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='completiondetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='goaldetail',
            name='points',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
