# Generated by Django 3.2 on 2022-12-07 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0019_challengecompletionmessage_challengemessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengemessages',
            name='friend_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_messages', to='challenge.friendchallenge'),
        ),
        migrations.AddField(
            model_name='challengemessages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
