# Generated by Django 3.2 on 2022-12-07 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_messageemoji_is_active'),
        ('challenge', '0020_auto_20221207_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengemessages',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_messages', to='common.messageemoji'),
        ),
    ]
