# Generated by Django 3.2 on 2022-12-12 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0021_alter_challengemessages_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendchallenge',
            name='challenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend_challenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendchallenge',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend_challenge', to=settings.AUTH_USER_MODEL),
        ),
    ]
