# Generated by Django 3.2 on 2022-12-12 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0022_auto_20221212_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendchallenge',
            name='challenger',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='friend_challenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendchallenge',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_challenge', to=settings.AUTH_USER_MODEL),
        ),
    ]
