# Generated by Django 3.2 on 2022-12-14 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0023_auto_20221212_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendchallenge',
            name='parent_challenge',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_friend_challenge', to='challenge.friendchallenge'),
        ),
    ]
